### ISSUE TITLE
Room creation wizard form

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#113]
Here are the steps we need to have in the wizard form:

- Emission mode: **broadcast** or **direct**
- Status: **public** or **private**
- Who can vote: everybody / only invited users / only users at a given place at a given moment
- Minimal number of votes for a track to be played

We should restrict how the user can customise the room. As proved by [Hick's Law](https://lawsofux.com/hicks-law/), the more choices there are, the longer it takes for a user to make a decision.
For instance, the user should not be able to customise exactly the minimum number of votes for a track to be played: three possibilities are enough and they can have a real meaning. For an online event, we might want a high number, when for a private session we might a low number.
For simplicity we could take inspiration from Uber application.

## Form integration in the current flow

When a user clicks on a track, we do not directly create the room. We must redirect the user to the wizard form.
Once the form has been completed, we redirect the user to the full screen player.

## Technical difficulties

We need to implement a places search.

We need to implement a date time picker. [Expo provides one](https://docs.expo.dev/versions/latest/sdk/date-time-picker/), but it does not work on the Web. We would need to code an alternative for the Web.

## Implementation

The wizard form would be driven by a state machine.

## UX/UI

We want to keep things simple.
We took inspiration from [Dribbble](https://dribbble.com/shots/15683004-My-Pet-mobile-app-design-concept?utm_source=Clipboard_Shot&utm_campaign=Merixstudio&utm_content=My%20Pet%20-%20mobile%20app%20design%20concept&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=Merixstudio&utm_content=My%20Pet%20-%20mobile%20app%20design%20concept&utm_medium=Social_Share).

## Tasks

 - [x] Create form steps on the client
 - [x] Take care of the form responsiveness
 - [x] Replace TextFields for physical constraints with suitable components (select, date time picker)
 - [x] Integrate the form in the flow
 - [x] Validate fields

**Comment by Devessier** [comment]
| | |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/29370468/131544276-c34f4451-a23c-4702-b7a7-f972fa620caf.png) | ![image](https://user-images.githubusercontent.com/29370468/131544304-6148b3bf-d689-4d30-818f-cbae02bbfb11.png)  |
| ![image](https://user-images.githubusercontent.com/29370468/131544335-43034700-84a7-47ee-94f1-471add240ed0.png)  | ![image](https://user-images.githubusercontent.com/29370468/131544347-626d3ebf-cfdc-421a-b812-9b13cd281074.png)  |

**Comment by prastoin** [comment]
I think we should also take a look to the spotify's settings input.
A lot of our potential settings could be abstract to a bool then to a simple toggle on off button

![image](https://user-images.githubusercontent.com/45004772/131627021-5406c6a2-cdb4-4f61-a153-0fead4838b3a.png)

**Comment by Devessier** [comment]
Spotify did a great job to design a settings screen.
In our case, we might want to be more user friendly in our way to guide users to create rooms.
Aesthetically two buttons, like those Uber uses, to distinguish between private and public modes are probably more talking than a toggle.
