### ISSUE TITLE
Add list of users in a mtv room

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#139]
It's time to add the list of users in the room to the music player.

This is how my fabulous team mate draw the view:
![image](https://user-images.githubusercontent.com/29370468/134491373-cbd271e5-dc9f-416e-a8ce-3594512be93a.png)

## TODO

- [x] Create a screen (and optionally StackNavigator to hold it)
- [x] The screen should have a search bar
- [x] Update `appScreenHeaderWithSearchBarMachine` so that upper machine is warn when input value changes
- [x] Create the user card
- [x] Add a three-dots button to user card that is pressable
- [x] Open a [Bottom Sheet Modal](https://gorhom.github.io/react-native-bottom-sheet/modal) when three-dots button is pressed
- [x] Let Bottom Sheet Modal contain a basic form to set selected user delegation rights
- [x] Write tests
