### ISSUE TITLE
MTV Search Engine

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#147]
## What we want

We want a FlatList with infinite scroll.
A search bar allows to filter results by mtv room name.
When search query is submitted, we fetch mtv rooms. While fetching, we show a loader.
We want to show for each mtv room its name creator, its creator, whether it's private or public.
We want to show private rooms first.
Clicking on a room makes the user join it.

## What we have currently

Currently we only fetch the room _uuid_.
Once a search query has been submitted, no submission can be made again.

## TODO

- [ ] Fetch room name and creator name
- [ ] Allow multiple submissions
- [ ] Show a loader while fetching
- [ ] Fetch rooms that match search query
- [ ] Add infinite loading handlers to FlatList
- [ ] Accept an offset and a limit in back-end mtv rooms searching route
