### ISSUE TITLE
MTV room chat

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#152]
It's time to implement a chat for MTV rooms.
We want something simple that is similar to Twitch chat.

We won't store messages in database.
Messages are sent to the server that broadcast them to every user, except the sender itself.

~~When we receive a new message, we want the flat list to scroll to it.~~
We display messages from oldest to newest.

Now we put the chat in a new tab of the player full screen.

~~Users should join the chat of the room when they arrive in the tab.~~

## Todo

- [x] Create a tab in fullscreen player
- [x] Create a FlatList to host messages
- [x] Create TextInput
- [x] Design message component
- [x] Join room socket when joining a room
- [x] Exit room socket when exiting a room
- [x] Create a socket listener in the server to receive messages and broadcast them to users
- [x] Listen to room messages in the client and push messages to a list
- [x] Send messages to server
