### ISSUE TITLE
Front-end MPE room creation

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#271]
The objective is to implement the most basic way to create a MPE room.
The system will be improved in the future.

## Todo

- [x] Create a button on the home screen to create a MPE room
- [x] Init a state machine to handle MPE rooms
- [x] Prepare the machine to manage several MPE rooms at the same time
- [x] When button on home screen is pressed, send a message to the state machine
