### ISSUE TITLE
Begin MPE room screen

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#272]
We need to scaffold the MPE room screen.
This screen will display the room information, its tracks list, etc.
For now it will be quite simple.

## Todo

- [x] Create a screen that takes as parameter the id of the room
- [x] Room information are picked from MPE global state machine by using screen id parameter
- [x] Create a new tab in the Bottom Bar, called _Library_ that will hold the MPE room screen
