### ISSUE TITLE
MPE Tracks List Editing - Front-end

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#276]
## Todo - Static Data

- [x] Create a FlatList item for each track in the playlist
- [x] Create _Add track_ button
- [x] When a track has been selected, add it to the playlist
- [x] Add buttons to move _up_ and _down_ tracks
- [x] When up and down buttons are pressed, move tracks accordingly
- [x] Add _Delete track_ button
- [x] When _Delete track_ button is pressed, delete the track
- [x] Freeze the UI some time after actions
