### ISSUE TITLE
MPE Deleting a track - Temporal

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#311]
Deleting tracks can not fail on Temporal side.
If the user tries to delete tracks that do not exist, this is not an issue. This behaviour can be due to tracks having been already deleted before the request is handled by Temporal.

## Todo

- [x] Receive a signal with tracks IDs to delete (`DeleteTracks`)
- [x] Ensure user has valid rights
- [x] Delete tracks from tracks list
- [x] Acknowledge the operation (request `/mpe/acknowledge-deleting-tracks`)
- [x] Create route `/mpe/delete-tracks` that sends `DeleteTracks` signal to the workflow
