### ISSUE TITLE
MPE Deleting a track - Server

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#312]
## Todo

- [x] Wait for `MPE_DELETE_TRACKS` WS event and request `/mpe/delete-tracks` route of Temporal
- [x] Create route `/mpe/acknowledge-deleting-tracks`
- [x] Send `MPE_DELETE_TRACKS_SUCCESS_CALLBACK` WS event to the device that deleted the tracks
- [x] Send `MPE_TRACKS_LIST_UPDATE` WS event to all other devices
