### ISSUE TITLE
MPE Deleting a track - Client

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#313]
## Todo

- [ ] When delete button is pressed on a track card, send a `MPE_DELETE_TRACKS` WS event with the id of the track
- [ ] Freeze the UI while waiting for server acknowledgement
- [ ] When receiving `MPE_DELETE_TRACKS_SUCCESS_CALLBACK`, assign tracks list and trigger a success toast
