### ISSUE TITLE
Export MPE to MTV - Plan

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#322]
## Behaviour

Any member of a MPE room can export it into a MTV by pressing a button.

[Behaviour schematized](https://stately.ai/viz/embed/cf71dcc1-f80d-484f-bab2-ed8452afc06e?mode=viz&panel=code&showOriginalLink=1&readOnly=1&pan=1&zoom=1&controls=1)

## Implementation

The user fills MTV room settings and confirms. The request is sent to MPE workflow, that forwards it to Adonis server alongside with MPE room current tracks list. From there, Adonis creates a MTV room the same way as in WS context.

A MPE room does not know that MTV rooms have been created from it. There is no link between MPE worklows and MTV workflows.

## Todo

- [ ] https://github.com/AdonisEnProvence/MusicRoom/issues/323
- [ ] https://github.com/AdonisEnProvence/MusicRoom/issues/324
- [ ] https://github.com/AdonisEnProvence/MusicRoom/issues/325

**Comment by Devessier** [comment]
Done!
