### ISSUE TITLE
MPE Creation - Client

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#328]
## Todo

- [x] When tracks in Search Tracks is pressed, show a modal with two buttons: _Create MTV_ and _Create MPE_
- [x] When _Create MTV_ button is pressed, redirect to MTV Creation Form
- [x] When _Create MPE_ button is pressed, redirect to MPE Creation Form
- [x] Create MPE Creation Form
- [x] When MPE Creation Form is submitted, send `MPE_CREATE_ROOM` to the server
- [x] When server acknowledges creation, spawn a Playlist actor for the room and redirect the user to the room
- [x] Listen for MPE room creation callback WS events even when not currently creating it
- [x] Test form using `@xstate/test`
- [x] Update integrations tests after rebasing
- [x] Update MPE E2E tests after rebasing
- [x] Update MTV E2E after having added the modal

## Notes

Where should MPE Creation Form screen be put?
Should it be attached to _Library_ bottom tab? Or to `RootNavigator`?

**Comment by prastoin** [comment]
> Should it be attached to _Library_ bottom tab? Or to `RootNavigator`?

We should be doing the same as for the MTV, unless i'm mistaken it's a rootNavigatorScreen
