### ISSUE TITLE
Other Users MPE Search Engine - Server

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#354]
## Todo

- [x] Create method `fetchUserRooms` on `MpeSearchRoomsHttpController`
- [x] Create route `/mpe/search-user-rooms` that uses `fetchUserRooms` method that takes a `userID` and a `tmpAuthUserID` as a body
- [x] This method returns all the **public** rooms of the given user if the correct user profile settings are set, precisely the `playtlistVisibility` value
- [x] if related user `playtlistVisibility` is available for the requesting user then send back the results else throw a 403 error
- [x] This method, if receiving a `searchQuery`, filters rooms by it
- [x] Pagination

**Comment by prastoin** [comment]
We should keep in mind that later when we will be working on the auth features, a user will be able to set as private this information

**Comment by Devessier** [comment]
Right.
We could do two things:

- When we fetch the information of a user, we get a flag indicating whether MPE rooms list is private or public
- In `fetchUserRooms` method we check for this authorization before making MPE rooms searching query
