### ISSUE TITLE
Other Users MPE Search Engine - Client

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#355]
## Todo

- [x] On user's profile screen put a link to Other Users MPE Search Engine screen with user's id
- [x] Create Other Users MPE Search Engine screen, waiting for a `userID` parameter
- [x] Use same state machine as MPE Search Engine and MTV Search Engine (handle pagination)
- [x] Fetch rooms from `/mpe/search-user-rooms`
- [x] When room is pressed, redirect the user to its screen
