### ISSUE TITLE
Visibility settings with proper defaults

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#418]
## Todo

- [x] Create `setting_visibilities` table (see definition below)
- [x] Seed `setting_visibilities` table in the migration with entries for: `PUBLIC`, `PRIVATE` and `FOLLOWERS_ONLY`
- [x] Create `playlists_visibility` column on `users` table that references `setting_visibilities`; required; defaults to `PUBLIC`
- [x] Create `relations_visibility` column on `users` table that references `setting_visibilities`; required; defaults to `PUBLIC`
- [x] Create `devices_visibility` column on `users` table that references `setting_visibilities`; required; defaults to `PUBLIC`
- [x] Create or update related Lucid models
- [x] Create a route to update playlists visibility; `POST` `/me/playlists-visibility`
- [x] Create a route to update relations visibility; `POST` `/me/relations-visibility`
- [x] Create a route to update devices visibility; `POST` `/me/devices-visibility`
- [x] Create a radio group for each setting on settings screen, that sends a request to the server automatically (with debounce client-side)

## `setting_visibilities` table

Columns:

- `uuid` which is a `UUID`; primary key
- `name` which is a `TEXT`; unique; will be mapped to a `z.enum` value

**Comment by prastoin** [comment]
>  Find the best way to assign PUBLIC visibility by default for all created users
I think this is possible inside the migration nor the lucid model

**Comment by prastoin** [comment]
>  Find the best way to assign PUBLIC visibility by default for all created users
I think this is possible inside the migration nor the lucid model

**Comment by Devessier** [comment]
> I think this is possible inside the migration nor the lucid model

Yes, I don't know if this is best to force it at the database level, or in our source code. Should we put this business logic in the database?

> Maybe should we also add to the setting_visibilities table a userID to be able to retrieve specific user information without having to retrieve the whole user ?

I was not planing to create an entry in `setting_visibilities` table for each user. To me, there are three entries in this table forever, and `users` table reference always one of them.

What performance issues were you talking about?

**Comment by prastoin** [comment]
> Yes, I don't know if this is best to force it at the database level, or in our source code. Should we put this business logic in the database?

We've been kinda doing it already, with mpeRoom and mtvRoom where inside pg migrations we specify that byDefault rooms have `is_open` to `true`

```ts
table.boolean('is_open').notNullable().defaultTo(true);
```

> I was not planing to create an entry in setting_visibilities table for each user. To me, there are three entries in this table forever, and users table reference always one of them.

Ok I wasn't on the hit, I think this is totally ok, hasOne Relationship will totally do the work
I was wondering a use case where we would like to retrieve user specific visibility information for a given props without having to retrieve the whole User model, anyway nevermind your solution is great

**Comment by Devessier** [comment]
> We've been kinda doing it already, with mpeRoom and mtvRoom where inside pg migrations we specify that byDefault rooms have is_open to true

Right. So we are going to use `defaultTo` too!

**Comment by Devessier** [comment]
We had to use `user.refresh()` to load the columns which value had been filled by the database.

We reverted the use of `defaultTo`, and instead used a `beforeCreate` hook.
