### ISSUE TITLE
Update nickname

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#420]
## Todo

- [x] Create a route to update its own nickname
- [x] Ensure the nickname is always unique _and case-insensitive (?)_
- [x] Create a field to update its own nickname
