### ISSUE TITLE
Link social accounts

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#421]
## Introduction

The link a google account the user musicroom account added value is the capacity to sign in using linked google account
A user that used a password email classic sign up and that ***has verified his email*** will be able from his profile settings to link a google account
The only added value for him will be the ability to connect to his music room account using the linked google account, we wont override any profile information that has been defined previously by the user itself

## Todo

client:
- [ ] Refactor the `ContinueWithGoogleButton` to allow it to target a specific route ( aka what to do with the retrieved accessToken )
- [ ] use the existing `ContinueWithGoogleButton` cmpnt inside the `myProfileSettingsScreen`
- [ ] Disable `link google account` if user already has a linked google account ( change button style e.g green ) => involves to update the user settings data type
- [ ] Extract the `accessToken` retrievement logic from the `appMachine` to be handling the edges cases in a machine inside the component `ContinueWithGoogleButton` itself ( will allow to do not duplicate this logic into two differents machines, also errors labels would be centralized ), or create a `GoogleAuthSessionMachine` that would be invoked inside the `appMachine` and the `userSettingsMachine`
- [ ] Handle server `link-google-social-account` response status using toast but also refresh user settings after a success to be able to disable the `ContinueWithGoogle` button in the client
- [ ] tests

server:
- [x] create a auth guarded and `hasVerifiedAccount` bounced `link-google-social-account` route that takes an `googleAccessToken`
- [x] add a handler to the created route where we exchange the `googleAccessToken` to for a user googleID only
If a matching user with same googleID is found throw an ACCOUNT_ALREADY_LINKED error
If no matching user is found update the related user googleID base entry ( SUCCESS )
If the user already has a linked google account throw an error ( should not happened as button should be disabled still to throw specific error will see how to deal with this in the client )
- [x] tests

**Comment by Devessier** [comment]
@prastoin Do we postpone this issue to Authentication development?

**Comment by prastoin** [comment]
Yes sounds like a good idea !

**Comment by prastoin** [comment]
Updating this issue content due to #544 merged

**Comment by Devessier** [comment]
> or create a GoogleAuthSessionMachine that would be invoked inside the appMachine and the userSettingsMachine

I vote for this solution!

**Comment by Devessier** [comment]
> If the user already has a linked google account throw an error

Maybe it could be handle in a bouncer action specific to this route?

**Comment by prastoin** [comment]
> > If the user already has a linked google account throw an error
> 
> Maybe it could be handled in a bouncer action specific to this route?

Good idea !

**Comment by prastoin** [comment]
Fix sign out button placement. put it inside settings dyanmic rendergin
