### ISSUE TITLE
Follow server

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#423]
In this issue will be treated the follow user server implementation

**Todo**

server:

Logic/
- [x] create a `post` http route `user/follow` that takes a `userID` in body **and a tmpAuthUserID** to be able to mock auth for the moment
- [x] handle the created route, add to the related `tmpAuthUserID` following list the given `userID`
- [x] ?? if given followed user is already in the following list throw an error ??
- [x] if the operation is a success send back an 200 response and compute a new `UserProfileInformation` to send back as response body, do not forget to maintain the new added `followingCounter` & `followerCounter` freshly added to the `UserProfileInformation` type

Data set up/
- [x] update get user profile information route to compute added props to `userProfileInformation`
- [x] Create a new pivot table `following_user_followed_user` with column: `following_user_uuid` and `followed_user_uuid` that refers to user table
- [x] inside the User model add a new `following` `ManyToMany` relationship toward other `User` model
- [x] inside the user model add a new `followers` `ManyToMany` relationship toward other `User` model

Both following and follower User model props `ManyToMany` configuration should look something like this:
```ts
    @manyToMany(() => User, {
        localKey: 'uuid', //following
        relatedKey: 'uuid', //followed

        pivotTable: 'following_user_followed_user',
        pivotForeignKey: 'following_user_uuid',
        pivotRelatedForeignKey: 'followed_user_uuid',
    })
    public following: ManyToMany<typeof User>;
    
    @manyToMany(() => User, {
        localKey: 'uuid', //followed
        relatedKey: 'uuid', //following

        pivotTable: 'following_user_followed_user',
        pivotForeignKey: 'followed_user_uuid',
        pivotRelatedForeignKey: 'following_user_uuid',
    })
   public follower: ManyToMany<typeof User>;
 ```

Note: https://github.com/AdonisEnProvence/MusicRoom/issues/426 should have been close before this issue
types:
- [x] add to `UserProfileInformation` a `followerCounter: number` and a `followingCounter: number`
- [x] add `following: boolean` to `UserProfileInformation`
