### ISSUE TITLE
Unfollow server

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#424]
In this issue will be treated the unfollow user server implementation

**Todo**

server:

- [x] create a `post` http route `user/unfollow` that takes a `userID` in body **and a tmpAuthUserID** to be able to mock auth for the moment
- [x] handle the created route, remove from the related `tmpAuthUserID` following list the given `userID`
- [x] ?? if given user is not in the following list throw an error ??
- [x] if the operation is a success send back an 200 response and recompute the unfollowed `UserProfileInformation` in response body
- [x] tests
