### ISSUE TITLE
User avatar

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#434]
We use a HTTP API that returns idempotent avatars: https://avatars.dicebear.com/.

URLs are of the form: `https://avatars.dicebear.com/api/:sprites/:seed.svg`.

We can use [Adventurer sprites](https://avatars.dicebear.com/styles/adventurer), they are quite funny. [Click to see an example](https://avatars.dicebear.com/api/adventurer/02e39849-afdc-4726-94c2-dc21e03740f4.svg)

We can use the UUID of the user as the seed. The effort to implement this feature would be minimal, and only client-side.

**question**: _Where do we want to display users' avatar?_

Component to use to render images in React Native: [Image](https://reactnative.dev/docs/image).

## Todo

- [x] Add user's avatar to `UserListItem` component
- [x] Display my avatar on My Profile screen
- [x] Display user's avatar on User Profile screen

**Comment by prastoin** [comment]
Really nice tool
I think that will do the work 100%
We could set the seed from user nickname, which is editable ? => more work just an idea
I'm not sure about the sprite family :laughing: they're quite sad or angry, I suggest [big smile](https://avatars.dicebear.com/styles/big-smile) that are IMO quite more joyfull haha

**Comment by prastoin** [comment]
> I think it would be better to have a predictable avatar. Github attributes an avatar to your account and you keep it until you upload your own profile picture. I think that changing your own avatar should not be a side effect, but something done in purpose. Maybe in the future we will implement avatar uploading.

You're right

> I totally agree! Go for this family.
Something really nice is the [initials family](https://avatars.dicebear.com/styles/initials).

As you wish, I guess the final decision will be taken when we will define the final and global app style layout
