### ISSUE TITLE
Create My Devices list

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#451]
## Todo

- [x] Create My Devices screen
- [x] Grab user's devices from `appUserMachine`
- [x] Display devices in a `FlatList`

**Comment by prastoin** [comment]
Reminder:
- [ ] e2e test for myDevicesList screen with several user devices
