### ISSUE TITLE
Get user's authenticated state and display signing in screen if unauthenticated

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#481]
## Todo

- [x] Update `appMachine` to check for user's authentication status initially
- [x] Create signing in form screen (ensure email is valid)
- [x] Redirect user to signing in form screen if she is not authenticated
- [x] Display Splash Screen until we determined if the user is authenticated or not
- [x] Display the application if the user is authenticated and **initialize the socket connection**
- [x] Send email and password to backend when the user submits signing form
- [x] Redirect user to the application if she has submitted correct credentials and **initialize the socket connection**
- [ ] Handle error returned by server for signing in

**Comment by Devessier** [comment]
Closed by https://github.com/AdonisEnProvence/MusicRoom/pull/490
