### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#484]
## Notes

Users need to keep the application open while getting the token we send them by email. If they close the application or go to another screen, they won't be able to go to the screen where they can fill the code, unless they launch another password reset procedure.

**Do we revoke all previous password reset tokens when a new one is generated for the same user?**

## Todo

- [x] On signing screen, add a button _Reset password_ that is enabled when a valid email has been filled in email field
- [x] When this button is clicked, we make a request to the backend asking to send a password reset email
- [x] Create a route to receive password reset requests
- [x] Generate a token, that expires after 15 minutes, for the user owning the received email and send the token in an email to the user
- [x] Rate limit password reset requests (at most three requests per hour)
- [x] If the rate limit has been reached, display an error to the user telling that they need to wait before beginning another password reset procedure
- [x] When the user clicks on _Reset password_ button, redirect her to a screen waiting for the token
- [x] Each time the user submits the token she entered, we make a request to ensure the token is valid
- [x] Create a route that returns whether a token exists
- [x] When the token is confirmed to exist, we redirect the user to a screen where she enters her new password
- [x] Create a route to resend a confirmation code for password reset, with rate limiting
- [x] Allow users to request another confirmation code for password reset
- [x] In this screen, we ask the user to supply her **strong** new password. Once the form is submitted, we send a request to the backend with **the token and the new password**
- [x] Create a route to handle new password submission, ensure the token is valid and different from the previous one, updates the password of the user owning the token and then revoke the token
- [x] If the submission succeeded, redirect the user to the application and **initialize the socket connection**
- [x] If the token had expired, redirect the user back to signing in screen and display an error

### `Token` model

- `uuid` of type `UUID`
- `user_uuid` of type `UUID` and references an instance of `User` model
- `type` of type `UUID` and references an instance of `TokenType` model (defined below)
- `token_value` of type `TEXT` (generated by something like [nanoid](https://github.com/ai/nanoid) and then **hashed before storing in the database**)
- `revoked` of type `BOOLEAN` that defaults to `FALSE`
- `createdAt` of type `TIMESTAMPTZ`
- `expiresAt` of type `TIMESTAMPTZ`

### Rate limiting

When we try to generate a password request token, we see get the count of password reset tokens generated in the last hour. If there are three tokens or more than three, we abort the procedure.

### Cron job to clean tokens

Tokens table can only grow if we never clean it. We need to clean it regularly, as it is meant to contain data with an expiration date.

### `TokenType` model

- `uuid` of type `UUID`
- `name` of type `TEXT` that can be a value of the corresponding zod enum we will create

Entries created with the table are:

- `PASSWORD_RESET`
- `EMAIL_VALIDATION` (see https://github.com/AdonisEnProvence/MusicRoom/issues/486)
