### ISSUE TITLE
Finalize global authentication and signing in

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#491]
## Todo

- [x] Type `/authentication/sign-in` request body
- [x] Type `/authentication/sign-in` response body
- [x] Save token returned by `/sign-in` to AsyncStorage if applicable
- [x] Send authorization token alongside every request, if applicable (on native platforms)
- [x] Migrate from `/authentication/me` to `/me/profile-information`
- [x] Handle errors in `/authentication/sign-in` as @prastoin did for `/authentication/sign-up`
- [x] Delete `/authentication/me` route and corresponding Controller method
