### ISSUE TITLE
Trim text filled by the user that is going to be displayed as is

### ISSUE THREAD

**Issue by prastoin** [AdonisEnProvence/MusicRoom#494]
We want to ensure inputs are trimmed. We want to perform this operation only on the backend.

- Trim at the beginning and at the end
- Require at least one character (after trimming)

## Todo

- [ ] Apply to username
- [ ] Apply to email
- [ ] Apply to MTV room name
- [ ] Apply to MPE room name

**Comment by prastoin** [comment]
also see about trimming given userNickname etc etc
