### ISSUE TITLE
Clients can request to go to the next track

### ISSUE THREAD

**Issue by Devessier** [AdonisEnProvence/MusicRoom#62]
When the user clicks on the _next_ button, the socket.io client must emit an event to the back-end. Be this event be called `GO_TO_NEXT_TRACK`.

The server should forward this event to Temporal by making an HTTP request. It should retrieve the workflow id and the run id of the Temporal workflow instance from `MtvRoom` Lucid model.

The Go REST API should expose a new endpoint that takes a workflow id and a run id in the body. This endpoint should send a signal to the correct Mtv Room Workflow instance. Be this signal be called `go-to-next-track`.
When the workflow receives the signal, it should send an event to the state machine. Be this event be called `GO_TO_NEXT_TRACK`.
When the state machine receives this event, if should assign the first item of `internalState.Tracks` slice to `internalState.CurrentTrack`, if there are items in `internalState.Tracks`, then it goes to `MtvRoomPlayingState` state. Otherwise it does nothing.

## Tasks

- [x] Emit `GO_TO_NEXT_TRACK` from client to server
- [x] Forward this event to Temporal from the server and verify it
- [x] Go to the next track in the workflow state machine
- [x] Write Temporal tests

**Comment by Devessier** [comment]
- [ ] Emit `GO_TO_NEXT_TRACK` from client to server
- [ ] Forward this event to Temporal from the server and verify it
- [ ] Go to the next track in the workflow state machine
